### ISSUE TITLE
only MAF format output has been implemented right now?

### ISSUE THREAD

**Issue by freedog8** [CshlSiepelLab/phast#16]
here is my test cmd:
gunzip -c maf/chr10.maf.gz | maf_parse -o FASTA -l hg19,panTro2 -g test.txt /dev/stdin |head

output:
Sorry, only MAF format output has been implemented right now.

$ gunzip -c maf/chr10.maf.gz | maf_parse --out-format FASTA -l hg19,panTro2 -g test.txt /dev/stdin |head
maf_parse: unrecognized option '--out-format'
Bad argument.  Try 'maf_parse -h' for help.

**Comment by siepellab** [comment]
Hello!

Try using msa_view which is also a part of the the PHAST package instead of maf_parse. Something like - 
gunzip -c maf/chr10.maf.gz | msa_view -o FASTA -l hg19,panTro2 -g test.txt /dev/stdin |head

Please let us know if this doesn't work. 
Also we have made a note of the bug in maf_parse and it should be corrected in the next version.
