### ISSUE TITLE
ERROR maf_read_subset: invalid idx_offset -2

### ISSUE THREAD

**Issue by Lucas-Maciel** [CshlSiepelLab/phast#17]
Hi,

I'm aligned 3 genomes (1 vs 2 and 1 vs 3) using lastal, and as TBA was not working for me, I tried to join these files using roast. However, when I tried to use phastCons I got this error message and I don't know what it means.

I also would like to ask which tool do you recommend to use to generate the inputs for phastCons.

Thank you

**Comment by siepellab** [comment]
Hello,
I think your input file may have multiple chromosomes. It is hard to say what the problem is without seeing the input file. 

But I would suggest checking that the MAF follows the following conventions:
- the first species in each block should be the same throughout the file. This is the "reference genome"
- the MAF is sorted by reference genome coordinate
- the MAF only contains a single chromosome from the reference genome. 

You can use mafSplit  to split the MAF file and the use maf_sort to sort the MAF. 
 
If that doesn't help, maybe you can reproduce the error in a small MAF file and send it to us and we can take a look.

**Comment by Ran-tian** [comment]
Hi,
I just used maf_parse to extract the cnee region from MAF based on the cnee.bed. But I got the warning "input MAF not sorted with respect to refseq.  Output files may not represent contiguous alignments". I guess maf_sort will resolve this problem, but did not find this tool in bin of phast. Where I can download it. Thank you.

**Comment by siepellab** [comment]
Hello!
maf_sort tool is a part of the multiz/tba package. -  http://www.bx.psu.edu/miller_lab/dist/multiz-tba.012109.tar.gz

Thanks!
Ritika
