### ISSUE TITLE
phastCons --viterbi failing on Mac OS Big Sur v11.3.1

### ISSUE THREAD

**Issue by keoughkath** [CshlSiepelLab/phast#46]
Hello, 

I'm attempting to run phastCons on Mac OS Big Sur v. 11.3.1. It works unless I invoke --viterbi, in which case I get the error `Illegal instruction: 4`. I suspect an issue with the pointer to CLAPACK, but I'm not sure. Any advice on how to get past this? 

I'm working with the latest version of phastCons downloaded from github (v1.6).

Sample command:

`phastCons sample.maf neutral_tree.mod --rho 0.3 --target-coverage 0.05 --expected-length 45 --no-post-probs --score --viterbi sample_phastCons.bed --seqname chrX -i MAF`

Output including error:

```
Reading tree model from neutral_tree.mod...
Reading alignment from sample.maf...
Creating 'conserved' and 'nonconserved' states in HMM...
Computing emission probs (state 0, cat 0, mod 0)...
Computing emission probs (state 1, cat 1, mod 1)...
Running Viterbi algorithm...
Illegal instruction: 4
```

Thanks,
Kathleen

**Comment by siepellab** [comment]
Hi Kathlenn, 
With Mac OS, you should have no issues with CLAPACK. LAPACK is built in Mac OSX. Did you install using the instructions here? 
http://compgen.cshl.edu/phast/gettingstarted.php

Thanks!
Ritika

**Comment by keoughkath** [comment]
Hi Ritika,

Yes, I followed those instructions. I'm not certain the error is CLAPACK, that was just a guess. Do you know what else might cause this error, and how I might fix it?

Thanks,
Kathleen

**Comment by siepellab** [comment]
Hi Kathleen, 
I am not sure. We haven't seen it before. 
It may be due to the Mac OS version. I will look into it. Meanwhile, maybe you could try it on a different machine to double-check if you have access to one. Also, you may want to go through something like this to see if it works. 
https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

It is a little challenging for me to debug because I can't replicate the problem on my end.

Thanks!
Ritika
